### PR TITLE
disable-shell.inc: add mksh shell

### PR DESCRIPTION
**Pull request by Ypnose**

### CODE REVIEW

**Comment by rusty-snake** [comment]
:1st_place_medal:  thanks.

**Comment by glitsj16** [comment]
For other shells we make user rc files read-only in disable-common.inc (section 'Startup files'). I'm not familiar with mksh, but online documentation seems to suggest it uses ${HOME}/.mkshrc. Should we add that path as read-only to disable-common.inc?

**Comment by rusty-snake** [comment]
yes. additional: have we any ro command for ksh startup file? I see no.

**Comment by glitsj16** [comment]
@rusty-snake good catch, that seems to be missing too

**Comment by Ypnose** [comment]
Thanks for merging and sorry for `*rc` files. I forgot it.

**Comment by glitsj16** [comment]
> Thanks for merging and sorry for *rc files. I forgot it.

Not a problem, it made us aware of a few omissions :-) Thanks again for the PR!

**Pull request merged**
