### PR TITLE
tidy up of disable-common.inc

### PR DESCRIPTION
**Pull request by smitsohu**
after the partial reversion of #1270

### CODE REVIEW

**Comment by SpotComms** [comment]
Are we sure we can't uncomment noexec for trash? I don't see why it would need that.

**Comment by smitsohu** [comment]
Are you referring to `noexec ${HOME}/.local/share`?

I agree, it should be safe to uncomment this line by default. I will add it to the PR

**Comment by smitsohu** [comment]
Let me add a thought:

Uncommenting `noexec ~/.local/share` makes sense mainly as a secure default when also `read-write ~/.local/share` is uncommented.
However, given how many applications store something in ~/.local/share and would be affected by this change, I admit there is a real risk for breaking (exotic?) features in some of them.
Maybe we can avoid potential trouble and instead better document in disable-common.inc that the two lines `read-write ~/.local/share` and `noexec ~/.local/share` belong and should be uncommented together?

**Comment by smitsohu** [comment]
Will close it for now, may reopen an improved request

**Pull request closed without merging**
