### PR TITLE
print rejected character in invalid filenames

### PR DESCRIPTION
**Pull request by smitsohu**
provide feedback about why a filename was rejected; see issue #3001

### CODE REVIEW

**Comment by smitsohu** [comment]
Actually this does not work well if the filename contains a control character. I would like to add a few lines to filter control characters as well (commit follows)

**Comment by smitsohu** [comment]
There needs to be a better error message if filename contains a control character. Just printing the filename does not work, as 1) these characters are not printable, and 2) the printed filename is sometimes hard to decipher garbage. So I'd propose to replace them with a `?`.

**Comment by netblue30** [comment]
Sure, let's go for '?', there is no better way. () are quite common in downloads.

**Comment by smitsohu** [comment]
Ok, I can remove () from the set.

**Comment by rusty-snake** [comment]
@smitsohu https://gitlab.com/Firejail/firejail_ci/-/jobs/422887566#L174

**Comment by smitsohu** [comment]
@rusty-snake Thanks for the pointer

**Pull request merged**
