### PR TITLE
Trim excess whitespace

### PR DESCRIPTION
**Pull request by a1346054**
Split from #4497 for further discussion.

For trailing whitespace a commit hook/CI check could be implemented, but most of the excess whitespace is within other text which makes it harder for automated tools to deal with. I mainly spotted it when reading through the files.

### CODE REVIEW

**Review by reinerh — APPROVED** [review]

**Review by kmk3 — CHANGES_REQUESTED** [review]
>      src/man/firejail-profile.txt                  | 32 ++++++++---------
>      src/man/firejail.txt                          | 36 +++++++++----------

Please leave existing double-spacing (".  ") as is.

It makes text much more readable in monospace fonts IMO.  It also makes editing
less error-prone, as it allows e.g.: vim to detect when a sentence ends vs when
you're just using an abbreviation (e.g.: "Mr.") and act accordingly on
commands that operate on sentences.

For a more extensive write-up, I found the following blog post:

* <http://stevelosh.com/blog/2012/10/why-i-two-space/>

It's kind of a rant, but it explains the main points.

Other than that, LGTM.

**Comment by a1346054** [comment]
The arguments are sound, I'll rework the PR to not remove those two spaces after a sentence.

The original reason why I removed them was to make it consistent with all the other text in firejail, where two spaces are not used.

**Comment by a1346054** [comment]
Rebased the PR to implement your review comments.

**Review by kmk3 — APPROVED** [review]
@a1346054 commented [on Sep 24](https://github.com/netblue30/firejail/pull/4575#issuecomment-926651114):

> The arguments are sound, I'll rework the PR to not remove those two spaces
> after a sentence.
> 
> The original reason why I removed them was to make it consistent

That makes sense.

> with all the other text in firejail, where two spaces are not used.

To be fair, there are a few more places where it's used (see with e.g.:
`git grep -I -n '\.  '`).

@a1346054 commented [on Sep 25](https://github.com/netblue30/firejail/pull/4575#issuecomment-927170464):

> Rebased the PR to implement your review comments.

Thanks for that and for the whitespace fixes.

**Pull request merged**
