### PR TITLE
pidgin: allow netlink

### LINKED ISSUE #5764: Firejail breaks Pidgin Chat Client
Since one week Pidgin doesn't start anymore with Firejail. I'm using Arch Linux 6.2.8-arch1-1 and Firejail --version 0.9.72.

The output when Pidgin is started with pidgin.profile:
~~~
Reading profile /etc/firejail/pidgin.profile
Reading profile /etc/firejail/pidgin.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 4564, child pid 4565
Private /etc installed in 8.20 ms
Private /usr/etc installed in 0.01 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: Cannot confine the application using AppArmor.
Maybe firejail-default AppArmor profile is not loaded into the kernel.
As root, run "aa-enforce firejail-default" to load it.
Child process initialized in 342.96 ms
Fontconfig error: Cannot load default config file: No such file: (null)
Pidgin 2.14.12 hat einen Speicherzugriffsfehler festgestellt und 
versucht, eine Core-Datei zu schreiben.  Dies ist ein 
Fehler im Programm und kein Fehler von Ihnen.

Wenn Sie den Absturz reproduzieren können, informieren Sie 
bitte die Entwickler mit einem Fehlerbericht auf:
https://pidgin.im/development/simpleticket/

Bitte geben Sie unbedingt an, was Sie getan haben als der 
Fehler aufgetreten ist, und posten Sie den Backtrace aus 
der Core-Datei. Falls Sie nicht wissen, wie man einen 
Backtrace erstellt, lesen Sie bitte die Informationen auf 
https://pidgin.im/development/wiki/GetABacktrace

Parent is shutting down, bye...
~~~

if it's important there's a output from `coredumpctl info /usr/bin/pidgin` attached:

[coredumpinfo_pidgin.txt](https://github.com/netblue30/firejail/files/11090281/coredumpinfo_pidgin.txt)

### PR DESCRIPTION
**Pull request by Xunil73**
Fixes #5764.

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]
LGTM

**Review by kmk3 — CHANGES_REQUESTED** [review]
Currently the commit message title is rather long (and it does not look like a
title), which makes it stand out in the git log:

```console
$ git show --pretty='%s' -s
added 'netlink', fixes netblue30/firejail:#5764, maybe working without it
$ git show --pretty='%s' -s | wc -m
74
```

The title is usually under 50~70 characters long; see the following for
details:

* <https://chris.beams.io/posts/git-commit/>

Can you amend the commit message to something like the following and
force-push?

```
pidgin: allow netlink

Fixes #5764.
```

Example:

```sh
git commit --amend
# (edit it)
git push --force-with-lease
```

**Review by glitsj16 — APPROVED** [review]
LGTM

**Review by kmk3 — CHANGES_REQUESTED** [review]
Note that a blank line is needed between the title and the body, or else git
treats both lines as the title:

```console
$ git show --pretty='%s' -s
pidgin: allow netlink Fixes #5764
```

**Review by kmk3 — APPROVED** [review]

**Comment by kmk3** [comment]
Merged, thanks!

**Pull request merged**
