### PR TITLE
Workflows: Change egress-policy to block

### PR DESCRIPTION
**Pull request by rusty-snake**

### CODE REVIEW

**Comment by rusty-snake** [comment]
> ```
> Error: fatal: unable to access 'https://github.com/netblue30/firejail/': Failed to connect to github.com port 443 after 12 ms: Connection refused
> ```

Ideas?

**Review by kmk3 — COMMENTED** [review]
@rusty-snake commented [on Nov 26](https://github.com/netblue30/firejail/pull/5485#issuecomment-1328084764):

> > ```
> > Error: fatal: unable to access 'https://github.com/netblue30/firejail/': Failed to connect to github.com port 443 after 12 ms: Connection refused
> > ```
> 
> Ideas?

Try to move the `harden-runner` step to after the `actions/checkout` step on each job.

**Comment by rusty-snake** [comment]
Ahh, we need to add

```yaml
    allowed-endpoints: >
      azure.archive.ubuntu.com:80
      debian.org:80
      github.com:443
      packages.microsoft.com:443
      ppa.launchpadcontent.net:443
      www.debian.org:443
      www.debian.org:80
      yahoo.com:1025
```

And we can consider `disable-sudo: true` for some jobs.

**Comment by kmk3** [comment]
@rusty-snake commented [on Nov 26](https://github.com/netblue30/firejail/pull/5485#issuecomment-1328107390):

> Ahh, we need to add
> 
> ```yaml
>     allowed-endpoints: >
>       azure.archive.ubuntu.com:80
>       debian.org:80
>       github.com:443
>       packages.microsoft.com:443
>       ppa.launchpadcontent.net:443
>       www.debian.org:443
>       www.debian.org:80
> ```

Makes sense to me.

> ```yaml
>       yahoo.com:1025
> ```

Why?

**Comment by rusty-snake** [comment]
Rebase, squashed and **fixed profile-check workflow which was changed on accidental**. ***Do not merge profile changes until this is merged***.

---

I think I change the build_and_test back to audit for now because `block` seems to make problems with the netfilter tests.

**Review by kmk3 — APPROVED** [review]
Nicely done; LGTM.

Suggestion for the commit message:

> ci: whitelist needed endpoints and block access to sudo
> 
> Disable sudo for codeql-analysis.yml and profile-checks.yml.

**Review by topimiettinen — APPROVED** [review]

**Comment by kmk3** [comment]
> Suggestion for the commit message:
> 
> > ci: whitelist needed endpoints and block access to sudo
> > 
> > Disable sudo for codeql-analysis.yml and profile-checks.yml.

@rusty-snake Thoughts on this?

I'd change at least the PR title to make it clearer (which is also usually what
goes in the RELNOTES).

**Comment by rusty-snake** [comment]
Actually I don't have a strong opinion.

**Pull request merged**
