### PR TITLE
Correct amule.profile for upnp

### PR DESCRIPTION
**Pull request by chrpinedo**
In order UPnP to work netlink protocol must be added

### CODE REVIEW

**Review by rusty-snake — COMMENTED** [review]
Since `netlink` opens a wide attack surface (to the kernel) it may be better to add it commented if UPnP is a rarely used feature of aMule.

**Comment by chrpinedo** [comment]
I agree with you that one commented line could be interesting to other users.

**Comment by smitsohu** [comment]
@chrpinedo Are you interested in adding a comment to the profile?

Otherwise I would suggest to merge as-is, in order to get the bug fixed.

**Comment by chrpinedo** [comment]
Since netlink protocol should be avoided when it is not required, I modified the commit to add one comment to the profile. If you agree, you could merge it.

**Review by rusty-snake — APPROVED** [review]

**Comment by smitsohu** [comment]
Merged!

**Pull request merged**
