### PR TITLE
WIP: --novideo option

### PR DESCRIPTION
**Pull request by Fred-Barclay**
Since `--private-dev` allows video devices as of 1328d523ed62dfcdb205580ce7c126813b592cb7, this gives us a way to block video devices in almost exactly the same way as `--nosound`.

Still a work in progress. Code needs cleanup and improvement, but
it does block /dev/video* in all of my tests so far.

Please review and let me know your thoughts, but don't merge! 😄 It's still got some issues to be fixed.

EDIT: sorry for the large diff. My editor (Atom) automatically removes trailing whitespace.

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
Did I mention my C stinks? No? Okay: my C stinks. 😁 
I'm getting this error at build (but it's not affecting running novideo as far as I can see):
```
sandbox.c: In function ‘sandbox’:
sandbox.c:814:3: warning: implicit declaration of function ‘fs_dev_disable_video’ [-Wimplicit-function-declaration]
   fs_dev_disable_video();
   ^~~~~~~~~~~~~~~~~~~~
```

**Comment by netblue30** [comment]
Looks fine, thanks. I'll have to fix my text editor, somehow it ends up saving tabs at the end of the line!

**Comment by Fred-Barclay** [comment]
Haha, no problem. 

One thing I've noticed is that novideo correctly blocks access to /dev/video0-9, but we still have full access to /dev/video10 or greater. I don't think anything greater than video9 would exist normally, but it's something to keep in mind.

**Comment by netblue30** [comment]
Is the same as /dev/nvidia0,1,2,3,... I guess it all depends on how many video cards and cameras the user has connected. We'll keep this in mind.

**Pull request merged**
