### PR TITLE
use ${DOWNLOADS} in lutris.profile

### PR DESCRIPTION
**Pull request by glitsj16**

### CODE REVIEW

**Comment by glitsj16** [comment]
@SkewedZeppelin I just spotted this. Not being familiar with lutris I'm wondering if there is a specific reason for using whitelist ${HOME}/Downloads instead of ${DOWNLOADS}?

**Review by SkewedZeppelin — APPROVED** [review]
Nice catch!

**Review by kmk3 — APPROVED** [review]
Darn, you beat me to it.

I did the same change 4 days ago, but as part of a larger branch.

At least let me do the `${DOCUMENTS}` one after this :p

**Comment by glitsj16** [comment]
@SkewedZeppelin Thanks for the review, much appreciated.

@kmk3

> I did the same change 4 days ago, but as part of a larger branch.

Hehe, I stumbled on this by accident, sorry to spoil your party...

> At least let me do the ${DOCUMENTS} one after this :p

That's a promise!

**Comment by kmk3** [comment]
> @kmk3
> 
> > I did the same change 4 days ago, but as part of a larger branch.
> 
> Hehe, I stumbled on this by accident, sorry to spoil your party...

It's all good hehe

> > At least let me do the ${DOCUMENTS} one after this :p
> 
> That's a promise!

Much appreciated :)

**Pull request merged**
