### PR TITLE
dia apparently wants access to python and crashes without

### PR DESCRIPTION
**Pull request by matu3ba**
Even though it is written in C, maybe another fix would be better

### CODE REVIEW

**Comment by matu3ba** [comment]
fixes #3030

**Comment by netblue30** [comment]
I see it also on Debian stable, thanks for the patch!

**Comment by rusty-snake** [comment]
Why disabling `disable-interpreters.inc`, is `include allow-pythonX.inc` not enough?

**Comment by netblue30** [comment]
You are right, I put a new fix in.

**Pull request merged**
