### PR TITLE
docs: warn about limitations of landlock

### PR DESCRIPTION
**Pull request by kmk3**
And mark it as experimental.

Relates to #6078.

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]

**Comment by glitsj16** [comment]
@kmk3 Although the Firejail/Landlock status is made much clearer in this PR it might still be nice to note that without having `landlock` in the `lsm=x,y,z` kernel parameter (cfr. apparmor) Firejail will ignore landlock commands.

Example bootloader lsm param for good Firejail support: `lsm=landlock,lockdown,yama,integrity,apparmor,bpf`

**Comment by kmk3** [comment]
> Although the Firejail/Landlock status is made much clearer in this PR it
> might still be nice to note that without having `landlock` in the `lsm=x,y,z`
> kernel parameter (cfr. apparmor) Firejail will ignore landlock commands.
> 
> Example bootloader lsm param for good Firejail support:
> `lsm=landlock,lockdown,yama,integrity,apparmor,bpf`

Landlock should work by default without needing to enable it.

Is there any distribution that disables it?

Example to check if it works:

```console
$ firejail --quiet --noprofile true
$ firejail --quiet --noprofile --landlock.enforce --landlock.fs.read=/foo true
Cannot start application: Permission denied
```

**Comment by glitsj16** [comment]
> Is there any distribution that disables it?

Not that I know of. I wasn't clear enough though, let me try to explain what I mean. If a user enables `AppArmor` as default security model on every boot via the `lsm` kernel parameter and `landlock` isn't part of that param, it does get disabled.

**Comment by kmk3** [comment]
> If a user enables `AppArmor` as default security model on every boot via the
> `lsm` kernel parameter and `landlock` isn't part of that param, it does get
> disabled.

I see it now; added an item about it.

**Comment by netblue30** [comment]
all set, thanks!

**Pull request merged**
