### PR TITLE
Alphabetise

### PR DESCRIPTION
**Pull request by Fred-Barclay**
(...it's just Fred being pedantic again.) :stuck_out_tongue_winking_eye: 

Seriously, this is my attempt to somewhat standardise the profiles and fix the occasional typo as well.

### CODE REVIEW

**Comment by reinerh** [comment]
Could you perhaps squash the commits into a single one to reduce some noise?
20 single commits with a single letter as commit message are not much descriptive/helpful.

**Comment by Fred-Barclay** [comment]
Hmmm... not familiar with squashing but I'll look into it unless @netblue30 beats me to it. :)

**Comment by Fred-Barclay** [comment]
Done!

**Comment by netblue30** [comment]
Merged, thanks.

**Pull request merged**
