### PR TITLE
add new syscalls from glibc 2.26-10

### PR DESCRIPTION
**Pull request by vn971**
File generated by ../tools/extract_syscall, as per instructions

### CODE REVIEW

**Comment by vn971** [comment]
This PR fixes https://github.com/netblue30/firejail/issues/1737

**Comment by vn971** [comment]
This pull is urgent as without it, all Qt applications _do not work_ with a seccomp whitelist. As far as I understood, Qt makes a `statx` call very early.
@netblue30 @Fred-Barclay

**Comment by Vincent43** [comment]
glibc 2.26-10 is Archlinux specific package version. I suppose those changes come from newer linux kernel api  - 4.14.
https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/glibc

**Comment by netblue30** [comment]
All merged, thanks!

**Comment by Fred-Barclay** [comment]
Thanks @vn971!
Interesting bit about Qt. Does someone know if it's related to the trouble we've seen with `QML_DISABLE_DISK_CACHE` and `QTWEBENGINE_DISABLE_SANDBOX`? #1723 for instance. 
cc @netblue30 @SpotComms @chiraag-nataraj @smitsohu

**Comment by vn971** [comment]
@Fred-Barclay I had hopes for that once you wrote it, but unfortunately, it doesn't work. I did the following:
1. reverted back to stock firejail on my system
2. used `--env=QML_DISABLE_DISK_CACHE=1 --env=QTWEBENGINE_DISABLE_SANDBOX=1` to start qBittorrent

Unfortunately, I still got:
```
Parent pid 25023, child pid 25024
Private /etc installed in 5.12 ms
Post-exec seccomp protector enabled
Warning fseccomp: syscall "statx" not available on this platform
Child process initialized in 58.51 ms

Parent is shutting down, bye...
```

**Comment by Fred-Barclay** [comment]
@vn971 I was thinking the other way around. 😁 Would this PR mean that we don't have to set the Qt environmental variables?

**Comment by Vincent43** [comment]
Qt qml cache bug is unrelated and will be fixed only in qt 5.11.

**Pull request merged**
