### PR TITLE
completed ecryptfs blacklist

### PR DESCRIPTION
**Pull request by vismir2**
added /home/.ecryptfs to blacklist

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
Wouldn't `blacklist ${HOME}/.ecryptfs` have the same effect? 
Or did I mess up with my PR? :question:

**Comment by vismir2** [comment]
Just making sure.

**Comment by netblue30** [comment]
Merged, thanks.

**Comment by SYN-cook** [comment]
@Fred-Barclay It's a bit late but I just wanted to add for sake of completeness why this was necessary: 
When ecryptfs is used for home folder encryption (e.g. by Ubuntu installer), the .ecryptfs folder, containing both the encrypted data and wrapped passphrases for _all_ users, is located in /home and not in ${HOME}. If an attacker would manage to steal these files, he could take all the time it needs to try to break the secret with brute-force (which might be impossible or easy), effectively bypassing all firejail protections.

**Comment by Fred-Barclay** [comment]
@SYN-cook I didn't think of that - thanks! :smile:

**Pull request merged**
