### PR TITLE
Fix ebook-viewer/calibre on manjaro

### LINKED ISSUE #2996: can't open Calibre ebook-viewer with net none
I can't open Calibre ebook-viewer 4.1.0-1 on Manjaro.
```
firejail --net=none /usr/bin/ebook-viewer
Reading profile /etc/firejail/ebook-viewer.profile
Reading profile /etc/firejail/calibre.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 5481, child pid 5482
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 188.81 ms
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
Qt: Session management error: Could not open network socket
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context

Parent is shutting down, bye...
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.13.1
Kernel Version: 4.19.78-1-MANJARO
OS Type: 64-bit

### PR DESCRIPTION
**Pull request by rusty-snake**
closes #2996

### CODE REVIEW

**Comment by smitsohu** [comment]
Would it make sense to add this to the calibre profile itself instead?

**Comment by rusty-snake** [comment]
Good question. IDK if calibre is affected. I will test this later.

**Comment by Vincent43** [comment]
Virtually all modern qt/gtk apps use dri.

**Comment by rusty-snake** [comment]
Now I found the time to test it. @smitsohu your right that make more sense. It looks like `calibre` is the library for your ebook and display the ebook with `ebook-viewer`  with is called in the calibre sandbox.

**Pull request merged**
