### PR TITLE
Wusc fixes

### PR DESCRIPTION
**Pull request by glitsj16**
Some fixes for #2972. @rusty-snake Apologies for not responding earlier to your excellent work with wusc, been a bit hectic on the personal front...

### CODE REVIEW

**Comment by rusty-snake** [comment]
Thanks. Maybe we can now move wusc to eo-common.profile since now eog and eom have it.

**Comment by rusty-snake** [comment]
@glitsj16 long time ago that I was using Arch. Is `/usr/share/ca-certificates` only used by Mozilla software or also by other e.g. wget,mpv,gnome-maps ?

**Comment by glitsj16** [comment]
@rusty-snake Good idea to move wusc to eo-common. Regarding `/usr/share/ca-certificates` I can confirm nothing besides Mozilla software uses that, at least not on Arch and Debian/Ubuntu, so no further action needs to be taken for that. During the coming week I'll have some time to test adding wusc to some more profiles. Nice addition :+1:.

**Comment by netblue30** [comment]
Sorry, wrong commit number (2992), it was supposed to be 2922.

**Pull request merged**
