### PR TITLE
Temporary fix for noexec ${HOME} breakage

### LINKED ISSUE #2385: Firefox cannot play Netflix videos if started in firejail
OS: Arch Linux 
 Kernel: x86_64 Linux 4.20.6-zen1-1-zen
 DE: XFCE4
 WM: Xfwm4
 CPU: Intel Core i5-4590 @ 4x 3.7GHz
 GPU: GeForce GTX 970

firejail version 0.9.58
Mozilla Firefox 65.0

I upgraded firejail (0.9.56-1 -> 0.9.58-1) on Jan 28th and since I cannot watch Netflix videos (DRM) in firefox. When I load one, just the gray background is shown. When I close firefox, the process(es) stay open in the background so I have to kill them.
firejail --debug or journalctl show nothing suspicious.
The config I use is the standard config minus `noroot` because of https://wiki.archlinux.org/index.php/Firejail#Proprietary_Nvidia_drivers

If I can do anything to help, I'll be glad to do so :-)

### PR DESCRIPTION
**Pull request by SkewedZeppelin**
We are probably missing more, feel free to commit directly to this branch

Closes #2385, #2383, #2380, #2378, #2375

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
@SkewedZeppelin is it safe to assume that pretty much any program that can play video is broken? If so I'll add VLC, xplayer, totem,...

**Comment by SkewedZeppelin** [comment]
@Fred-Barclay I don't think that is the case

**Comment by Vincent43** [comment]
@Fred-Barclay only those which try to execute binaries from `$HOME` are affected

@SkewedZeppelin you may add comments why it's disabled. Also `apparmor` should have same effect as `noexec $HOME` so we either have to disable it as well or point users to [workaround](https://github.com/netblue30/firejail/blob/master/etc/firejail-default#L80).

**Comment by smitsohu** [comment]
Does this qualify for a bugfix release?
@netblue30

**Comment by netblue30** [comment]
Yes, bugfix release next Friday, Feb 8. Let's check it in!

**Pull request merged**
