### PR TITLE
Enable KVM on Android Studio

### PR DESCRIPTION
**Pull request by rccavalcanti**
Current profile denies access to /dev/kvm.

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
G'day @rccavalcanti !
What happens with the current profile - that is, why does AndroidStudio need access to /dev/kvm?
Thanks!
Fred

**Comment by rccavalcanti** [comment]
Hi @Fred-Barclay,
KVM is used for hardware acceleration on virtual devices (AVD Manager). Info [here](https://developer.android.com/studio/run/emulator-acceleration#vm-linux).

With the current profile, AVD Manager throws "/dev/kvm is not found". The device I have can't even be started, as I get "KVM is required to run this AVD".

**Comment by Fred-Barclay** [comment]
Merged, thanks!

**Comment by saddy001** [comment]
For me it throws permission denied for /dev/kvm in the current version. When I look at permissions in the jail:
```
ls -hla /dev/kvm 
crw-rw---- 1 nobody nogroup 10, 232 Okt 22 12:10 /dev/kvm
```

Is there a workaround?

**Pull request merged**
