### PR TITLE
whitelist-usr-share-common.inc

### PR DESCRIPTION
**Pull request by rusty-snake**
Any suggestions,  testing, ... welcome :wink: .

Related issue:  #2505

### CODE REVIEW

**Comment by rusty-snake** [comment]
```
git clone --depth 1 https://github.com/netblue30/firejail.git
cd firejail
git fetch origin pull/2972/head
git co FETCH_HEAD
./configure --prefix=/usr
make
sudo make install-strip
```

**Comment by rusty-snake** [comment]
`whitelist /usr/share/*` does not whitelist all in /usr/share, it whitelist nothing. But does't matter, also rhytmbox is broken with wusc.inc. It looks like GNUTLS don't like whitelisting in /usr/share? strace say that there are no missing whitelist paths.

**Comment by rusty-snake** [comment]
```python3
#!/usr/bin/env python3

import sys, os

BUILD_PROFILE = f"{sys.argv[1]}.profile-tmp"
WUSC = "/etc/firejail/whitelist-usr-share-common.inc"

os.system(f"firejail --build={BUILD_PROFILE} {sys.argv[1]} 2>/dev/null >/dev/null")

wusc = open(WUSC, "r")
profile = open(BUILD_PROFILE, "r")

for line in profile:
    if line.startswith("whitelist /usr/share"):
        if "//" in line:
            line = line.replace("//", "/")
        if line not in wusc:
            print(line, end='')
        wusc.seek(0)
```

**Comment by rusty-snake** [comment]
```
firejail --trace=FILE PROGRAM
grep -oE "/usr/share//?[^/:]+" FILE | sort -u
```

**Comment by rusty-snake** [comment]
The current state: wusc.inc seems to be more or less complete. wusc.inc is enabled in 29 profiles. I'm running with firejail from this PR the last two weaks under Fedora 30 GNOME without issues (or fixed issues). I've done a few tests in a debian VM over the last few days.

The next goals whould be testing this under more distros since /usr/share has sometimes distros specific paths and add ing wusc.inc to more profiles.

**Comment by netblue30** [comment]
@rusty-snake - what's the status? Do we merge it?

**Comment by rusty-snake** [comment]
I'll merge it in a few hours if nobody stops me. If there is any distro specific missing, we will see it.

**Pull request merged**
