### PR TITLE
Add profiles for IntelliJ IDEA and Android Studio

### PR DESCRIPTION
**Pull request by SpotComms**
Profile for the open source Java IDE, IntelliJ IDEA.
- The IDEA profile is for Community Edition, although it'd prob work with Ultimate/others with minor tweaks.
- Android Studio is based off of Community Edition. Did not test AVD emulator.

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
Thanks! I don't know much about either of these programmes, but do we have to noblacklist ~/.gnupg?

**Comment by SpotComms** [comment]
I have removed ~/.gnupg. IntelliJ doesn't have built-in git commit signing, and I'm sure most prefer a full terminal compared to the integrated one.

**Comment by Fred-Barclay** [comment]
Merged, thanks!
I removed the `noblacklist ~/.ssh` line in both profiles... is it necessary to have ssh config access? If so we can add it back in. 😄

**Comment by SpotComms** [comment]
.ssh is needed for pushing and pulling git repos.

**Comment by Fred-Barclay** [comment]
You're right, some git repos need ssh. I'll add it back.

**Pull request merged**
