### PR TITLE
GitHub stroking out on my end. :)

### PR DESCRIPTION
**Pull request by Fred-Barclay**
Hi netblue30. I hate to ask, but could you merge this? Apparently there were multiple file conflicts between your repo and my fork ("unmerged paths" to be specific). I've discarded my changes and kept yours when merging, so merging will change nothing on your end and make my fork happy. :)

(Or if this is related to my abysmal understanding of git and I should be taking another step entirely, please let me know.)
Thanks!

### CODE REVIEW

**Comment by reinerh** [comment]
Please rebase your forked branch onto netblue's branch.
It doesn't make much sense to merge commits that don't do anything.

**Comment by netblue30** [comment]
0ad profile is in, I already merged your patch. I think you need to clone the repository again.

**Comment by Fred-Barclay** [comment]
Sorry guys. Coding I can do (well, usually). GitHub? It proves it's superiority to me every day. :)

**Comment by netblue30** [comment]
No problem.

**Pull request closed without merging**
