### PR TITLE
opt-in: hide blacklisted files in /etc 

### LINKED ISSUE #5010: Firefox under Firejail can't make new connections after switching network connection methods
### Description
After using Firefox for a bit on WiFi and then experiencing a network failure, when I go to change my network connection method to Ethernet, I cannot open or refresh pages in Firefox. 

Connections will time out and I'll have to close the browser and open it again in order to load or refresh pages.

### Steps to Reproduce
Open Firefox with Firejail, let it run for a bit. After experiencing a network connection error, change your connection via a separate network device. Go back to Firefox and try to open "google.com". 

### Expected behavior
I should be able to resume using the browser after experiencing a network failure and/or network device change.

### Actual behavior
After network failure/network device change, trying to open new pages or refreshing tabs results in those tabs eventually timing out without loading. The browser must exit and start again for it to work.

### Behavior without a profile
This does not seem to be an error with Firejail-less Chromium or when I've tried to replicate the issue in Firefox without Firejail.

### Additional context


### Environment
- Manjaro unstable
- firejail version 0.9.68                                                                                                                                       


### Checklist

<!--
Note: Items are checked with an "x", like so:

- [x] This is a checked item.
-->

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
$ LC_ALL=C firejail firefox  --new-instance --profile "tmp" --private-window "https://imgur.com" 
Reading profile /etc/firejail/firefox.profile                                                                                                                 
Reading profile ~/.config/firejail/firefox.local                                                                                                     
Reading profile /etc/firejail/whitelist-usr-share-common.inc                                                                                                  
Reading profile /etc/firejail/firefox-common.profile                                                                                                          
Reading profile /etc/firejail/disable-common.inc                                                                                                              
Reading profile /etc/firejail/disable-devel.inc                                                                                                               
Reading profile /etc/firejail/disable-exec.inc                                                                                                                
Reading profile /etc/firejail/disable-interpreters.inc                                                                                                        
Reading profile /etc/firejail/disable-proc.inc                                                                                                                
Reading profile /etc/firejail/disable-programs.inc                                                                                                            
Reading profile /etc/firejail/whitelist-common.inc                                                                                                            
Reading profile /etc/firejail/whitelist-run-common.inc                                                                                                        
Reading profile /etc/firejail/whitelist-runuser-common.inc                                                                                                    
Reading profile /etc/firejail/whitelist-var-common.inc                                                                                                        
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,                                                                                        
Ignoring "dbus-user.own org.mozilla.Firefox.*" and 2 other dbus-user filter rules.                                                                            
Parent pid 690627, child pid 690628                                                                                                                                                                                                                          
Warning: logind not detected, nogroups command ignored                                                                                                        
Warning: logind not detected, nogroups command ignored                                                                                                        
Warning: logind not detected, nogroups command ignored                                                                                                        
Warning: /sbin directory link was not blacklisted                                                                                                             
Warning: /usr/sbin directory link was not blacklisted                                                                                                         
Warning: logind not detected, nogroups command ignored                                                                                                        
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,                                                                                        
Warning: logind not detected, nogroups command ignored                                                                                                        
Child process initialized in 96.16 ms  
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

```
output goes here
```

</p>
</details>

### LINKED ISSUE #5230: /etc is unwritable on --chroot on debootstrap system
### Description

Following the documentation at https://firejail.wordpress.com/documentation-2/basic-usage/ concerning the usage of firejail for creating an isolated debootstrap system, I am unable to create a user account and installing packages via. `apt` result in errors when attempting write to /etc.

### Steps to Reproduce

(as root)

1. `emerge -qv firejail`
2. `echo "force-nonewprivs yes" >> /etc/firejail/firejail.config`
3. `mkdir /jail`
4. `debootstrap --arch=amd64 stable /jail`
5. `LC_ALL=C TERM=xterm-color firejail --noprofile --chroot=/jail --shell=/bin/bash` (note this already deviates from the documentation as the provided command will actually fail without setting `--shell`)
6. `adduser foo`

### Expected behavior

```
$ adduser foo
Adding user `foo' ...
Adding new group `foo' (1000) ...
etc. etc.
```

### Actual behavior

```
$ adduser foo
Adding user `foo' ...
Adding new group `foo' (1000) ...
groupadd: failure while writing changes to /etc/group
adduser: `/sbin/groupadd -g 1000 foo' returned error code 10. Exiting.
```

### Additional context

I'm not sure if this is really a bug or merely a configuration error or a lack of concise documentation, but this occurs using the default firejail v0.9.68 as it comes on Gentoo with the only change in configuration being `force-nonewprivs yes` as suggested by the documentation.

Similar commands such as `useradd` or unrelated commands like calling `apt` are also failing:

```
$ useradd foo
useradd: failure while writing changes to /etc/passwd
```

```
$ apt install htop
...
ldconfig: Renaming of /etc/ld.so.cache~ to /etc/ld.so.cache failed: Device or resource busy
dkpg: error processing package libc-bin (--configure):
  installed libc-bin package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
  libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Environment

- Linux distribution and version (e.g. "Ubuntu 20.04" or "Arch Linux")
```
Linux home 5.15.41-gentoo-x86_64 #1 SMP Thu Jun 30 20:08:43 UTC 2022 x86_64 AMD Ryzen 7 PRO 5850U with Radeon Graphics AuthenticAMD GNU/Linux
```

- Gentoo USE flags
```
X chroot dbusproxy file-transfer globalcfg network private-home userns -apparmor -contrib -test
```

- Firejail version (`firejail --version`).

```
firejail version 0.9.68

Compile time support:
	- always force nonewprivs support is disabled
	- AppArmor support is disabled
	- AppImage support is enabled
	- chroot support is enabled
	- D-BUS proxy support is enabled
	- file transfer support is enabled
	- firetunnel support is disabled
	- networking support is enabled
	- output logging is enabled
	- overlayfs support is disabled
	- private-home support is enabled
	- private-cache and tmpfs as user enabled
	- SELinux support is disabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
    - Yes, a regular chroot lets me interact with my Debian installation as normal, but that defeats the purpose.
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
    - `--noprofile` as per the docs.
- [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

```
$ LC_ALL=C TERM=xterm-color firejail --noprofile --chroot=/jail --shell=/bin/bash --debug
Command name #/bin/bash#
Enabling IPC namespace
Using the local network stack
Command name #/bin/bash#
Enabling IPC namespace
Using the local network stack
Initializing child process
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Creating empty /run/firejail/mnt/seccomp directory
Creating empty /run/firejail/mnt/seccomp/seccomp.protocol file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec32 file
Mounting /dev on chroot /dev
Updating chroot /etc/resolv.conf
Chrooting into /jail
Mounting /proc filesystem representing the PID namespace
Mounting tmpfs on /var/lock
Mounting tmpfs on /var/tmp
Mounting tmpfs on /var/log
Create the new utmp file
Mount the new utmp file
blacklist /run/firejail/dbus
Mounting read-only /proc/sys
Remounting /sys directory
Disable /sys/firmware
Disable /sys/power
Disable /sys/kernel/debug
Disable /sys/kernel/vmcoreinfo
Disable /proc/sys/fs/binfmt_misc
Disable /proc/sys/kernel/core_pattern
Disable /proc/sys/kernel/modprobe
Disable /proc/sysrq-trigger
Disable /proc/sys/vm/panic_on_oom
Disable /proc/irq
Disable /proc/bus
Disable /proc/timer_list
Disable /proc/kcore
Disable /proc/kallsyms
Disable /boot
Disable /dev/port
Disable /mnt
Disable /media
Disable /run/mount
Disable /sys/fs
Disable /sys/module
rebuilding /etc directory
Creating empty /run/firejail/mnt/dns-etc/rc2.d directory
Creating empty /run/firejail/mnt/dns-etc/xattr.conf file
Creating empty /run/firejail/mnt/dns-etc/selinux directory
Creating empty /run/firejail/mnt/dns-etc/fstab file
Creating empty /run/firejail/mnt/dns-etc/group- file
Creating empty /run/firejail/mnt/dns-etc/apt directory
Creating empty /run/firejail/mnt/dns-etc/ca-certificates.conf file
Creating empty /run/firejail/mnt/dns-etc/resolv.conf file
Creating empty /run/firejail/mnt/dns-etc/rcS.d directory
Creating empty /run/firejail/mnt/dns-etc/kernel directory
Creating empty /run/firejail/mnt/dns-etc/timezone file
Creating empty /run/firejail/mnt/dns-etc/passwd file
Creating empty /run/firejail/mnt/dns-etc/ld.so.cache file
Creating empty /run/firejail/mnt/dns-etc/ld.so.conf file
Creating empty /run/firejail/mnt/dns-etc/rc0.d directory
Creating empty /run/firejail/mnt/dns-etc/host.conf file
Creating empty /run/firejail/mnt/dns-etc/gshadow file
Creating empty /run/firejail/mnt/dns-etc/adduser.conf file
Creating empty /run/firejail/mnt/dns-etc/systemd directory
Creating empty /run/firejail/mnt/dns-etc/nsswitch.conf file
Creating empty /run/firejail/mnt/dns-etc/ld.so.conf.d directory
Creating empty /run/firejail/mnt/dns-etc/debian_version file
Creating empty /run/firejail/mnt/dns-etc/subgid file
Creating empty /run/firejail/mnt/dns-etc/cron.d directory
Creating empty /run/firejail/mnt/dns-etc/rc6.d directory
Creating empty /run/firejail/mnt/dns-etc/mke2fs.conf file
Creating empty /run/firejail/mnt/dns-etc/default directory
Creating empty /run/firejail/mnt/dns-etc/deluser.conf file
Creating empty /run/firejail/mnt/dns-etc/dpkg directory
Creating empty /run/firejail/mnt/dns-etc/pam.d directory
Creating empty /run/firejail/mnt/dns-etc/subuid file
Creating empty /run/firejail/mnt/dns-etc/rc3.d directory
Creating empty /run/firejail/mnt/dns-etc/issue.net file
Creating empty /run/firejail/mnt/dns-etc/bash.bashrc file
Creating empty /run/firejail/mnt/dns-etc/profile.d directory
Creating empty /run/firejail/mnt/dns-etc/netconfig file
Creating empty /run/firejail/mnt/dns-etc/rc5.d directory
Creating empty /run/firejail/mnt/dns-etc/shells file
Creating empty /run/firejail/mnt/dns-etc/ca-certificates directory
Creating empty /run/firejail/mnt/dns-etc/.pwd.lock file
Creating empty /run/firejail/mnt/dns-etc/update-motd.d directory
Creating empty /run/firejail/mnt/dns-etc/shadow- file
Creating empty /run/firejail/mnt/dns-etc/hostname file
Creating empty /run/firejail/mnt/dns-etc/debconf.conf file
Creating empty /run/firejail/mnt/dns-etc/passwd- file
Creating empty /run/firejail/mnt/dns-etc/environment file
Creating empty /run/firejail/mnt/dns-etc/logrotate.d directory
Creating empty /run/firejail/mnt/dns-etc/e2scrub.conf file
Creating empty /run/firejail/mnt/dns-etc/opt directory
Creating empty /run/firejail/mnt/dns-etc/rc1.d directory
Creating empty /run/firejail/mnt/dns-etc/libaudit.conf file
Creating empty /run/firejail/mnt/dns-etc/ssl directory
Creating empty /run/firejail/mnt/dns-etc/gai.conf file
Creating empty /run/firejail/mnt/dns-etc/bindresvport.blacklist file
Creating empty /run/firejail/mnt/dns-etc/cron.daily directory
Creating empty /run/firejail/mnt/dns-etc/gss directory
Creating empty /run/firejail/mnt/dns-etc/profile file
Creating empty /run/firejail/mnt/dns-etc/motd file
Creating empty /run/firejail/mnt/dns-etc/shadow file
Creating empty /run/firejail/mnt/dns-etc/skel directory
Creating empty /run/firejail/mnt/dns-etc/pam.conf file
Creating empty /run/firejail/mnt/dns-etc/group file
Creating empty /run/firejail/mnt/dns-etc/terminfo directory
Creating empty /run/firejail/mnt/dns-etc/issue file
Creating empty /run/firejail/mnt/dns-etc/security directory
Creating empty /run/firejail/mnt/dns-etc/login.defs file
Creating empty /run/firejail/mnt/dns-etc/init.d directory
Creating empty /run/firejail/mnt/dns-etc/rc4.d directory
Creating empty /run/firejail/mnt/dns-etc/alternatives directory
Mount-bind /run/firejail/mnt/dns-etc on top of /etc
Current directory: /root
Mounting read-only /run/firejail/mnt/seccomp
279 109 0:50 /seccomp /run/firejail/mnt/seccomp ro,nosuid - tmpfs tmpfs rw,mode=755,inode64
mountid=279 fsname=/seccomp dir=/run/firejail/mnt/seccomp fstype=tmpfs
Seccomp directory:
ls /run/firejail/mnt/seccomp
drwxr-xr-x root     root             120 .
drwxr-xr-x root     root             180 ..
-rw-r--r-- root     root             568 seccomp
-rw-r--r-- root     root             432 seccomp.32
-rw-r--r-- root     root               0 seccomp.postexec
-rw-r--r-- root     root               0 seccomp.postexec32
No active seccomp files
NO_NEW_PRIVS set
Drop privileges: pid 1, uid 0, gid 0, force_nogroups 0
No supplementary groups
Closing non-standard file descriptors
Starting application
LD_PRELOAD=(null)
Starting /bin/bash shell
execvp argument 0: /bin/bash
The new log directory is /proc/14520/root/var/log
```

</p>
</details>

### PR DESCRIPTION
**Pull request by smitsohu**
Closes #5010
Closes #5230

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]
LGTM. Nice to get these fixes in 0.9.72 (I hope)!

**Comment by smitsohu** [comment]
Thanks @glitsj16 

Unfortunately I think I will need to update the pull request one more time, also to fix the failing test, sorry for that! Converting to draft ...

**Comment by netblue30** [comment]
The fix is straightforward - @smitsohu, let's do like this:

I'll grab it as is and fix whatever is to fix in "make test", and you check in directly whatever else you need to modify. Then, I'll release it, quite simple!

**Comment by smitsohu** [comment]
@netblue30 I think it should be ok the way it is now. Maybe I rearrange it at  a later timepoint, after the release is out.

**Comment by kmk3** [comment]
Related commit: ba9c9699e ("Removing blacklisted files from top level /etc
directory if the filse were blacklisted", 2021-07-14).

For future reference, the default behavior on 0.9.68 and 0.9.70 (due to the
above commit) is likely similar to having `etc-no-blacklisted yes`.

**Pull request merged**
