### PR TITLE
noqueue not exposed on older kernels; pfifo_fast is default qdisc

### PR DESCRIPTION
**Pull request by reinerh**

### CODE REVIEW

**Comment by KellerFuchs** [comment]
It looks to me as if the `test/utils/seccomp.exp` is an unrelated fix.
Perhaps it should be in a separate commit?

**Comment by reinerh** [comment]
I think it was trivial enough to keep it in one commit.
But have split it up now.

**Comment by KellerFuchs** [comment]
@reinerh It's more than it is kinda confusing when using `git-blame`, since it would say “this line comes from this seemingly-unrelated commit”.
Thanks a lot.

**Comment by netblue30** [comment]
Merged, thanks.

**Pull request merged**
