### PR TITLE
Okular and Gwenview profiles, Baloo blacklist

### PR DESCRIPTION
**Pull request by SYN-cook**
- Gwenview: This patch is necessary for the KDE4 build, the KF5 build doesn't need any of it.
- Okular: It was already described in #421, and I can confirm that printing from okular is not possible without `private-bin lpr`

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
Thanks @SYN-cook .
I wonder if we should uncomment the updated private-bin lines?

**Comment by SYN-cook** [comment]
For Gwenview I personally don't see a problem with uncommenting shell none and private-bin, actually. It is a bit speculative, but if there is a new release of Firejail this year and Gimp 2.10 is not released yet (it has been announced for 2017), one could maybe consider appending the private-bin line already in advance.

Uncommenting private-bin in the okular profile is also perfectly fine for "normal" use, from my experience. The only thing that probably wouldn't work is editors (you can see in the settings that there is some kind of support in okular). I've looked it up and the editor support is only for LATeX, which I never use. 

Btw, the current profile also works with new okular version 1.x, I just tried it out. Only the blacklist/noblacklisting needs another little update...

**Comment by SYN-cook** [comment]
So let's uncomment private-bin in the gwenview profile?

**Comment by Fred-Barclay** [comment]
> So let's uncomment private-bin in the gwenview profile?
Yeah, let's try it. :smile: 

Thanks for the PR!

**Pull request merged**
