### PR TITLE
Use whitelisting for video players

### PR DESCRIPTION
**Pull request by Fred-Barclay**
Switches video players over to a whitelist basis.

I've tested celluloid, vlc, and xplayer and they seem to be fine - would really appreciate additional testing! 😃

### CODE REVIEW

**Comment by glitsj16** [comment]
Looks fine. As I have run with whitelisting profiles for mplayer and mpv for a long time I can confirm both work as expected.

On the matter of completely removing disable-xdg.inc I also never whitelist ${DESKTOP} and ${DOCUMENTS} in media player profiles.

**Comment by Fred-Barclay** [comment]
Thanks @rusty-snake and @glitsj16 !

To address your thoughts...

1/2 my completely unproven gut feeling is that folks would be more likely to have videos on Desktop than Documents. Perhaps remove Documents but keep Desktop visible in the sandbox??

3. I believe we have to remove `disable-xdg.inc` or (alternatively) noblacklist everything but Documents (and potentially Desktop). At that rate it might be more clear to just blacklist Documents instead of having `include disable-xdg.inc` followed by a bunch of noblacklists.

4. Definitely will fix this one, thanks!

**Comment by glitsj16** [comment]
> 1/2 my completely unproven gut feeling is that folks would be more likely to have videos on Desktop than Documents. Perhaps remove Documents but keep Desktop visible in the sandbox??

I can see your point. Personally I can live with removing ${DOCUMENTS} and keeping ${DESKTOP}.

About point 3. I have come across situations like these before a few times, meaning that whatever one opts for, users are going to have to decide on loosening/tightening individual profiles via *.local files. In such cases I think it makes more sense to make it harder on users to loosen sandboxes, instead of 'punishing' users that favor more tightened profiles. So in this case I would opt for **keeping** include disable-xdg.inc, _even if that means having a few more lines in the profiles_. Hope this makes sense, I might have one of those 'fuzzy logic' brain cells :)

**Comment by curiosityseeker** [comment]
I also vote for removing ${DOCUMENTS} and keeping ${DESKTOP} - but what about making the latter _read-only_?

**Comment by rusty-snake** [comment]
> but what about making the latter read-only?

IMHO we should add
```
read-only ${HOME}
read-write ${HOME}/.config/foo
read-write ${HOME}/.local/share/foo
```
to more profiles in general.

**Comment by Fred-Barclay** [comment]
> I also vote for removing ${DOCUMENTS} and keeping ${DESKTOP} - but what about making the latter _read-only_?

My concern is with editing file metadata here - for example I believe VLC lets you easily change artist/album names? Maybe not too much an issue with videos but it's not unreasonable to expect people to play i.e. mp3s with video players and read-only access would be an issue here.


Also unrelated side note - I messed up by pushing to`master` on my fork for this PR - might have to close and send in a similar one, apologies for any inconvenience. 😄

**Comment by curiosityseeker** [comment]
> My concern is with editing file metadata here - for example I believe VLC lets you easily change artist/album names? Maybe not too much an issue with videos but it's not unreasonable to expect people to play i.e. mp3s with video players and read-only access would be an issue here.

I understand, and I think you're right. Nevertheless I feel a bit uneasy. Write permission for the supported extensions would be probably preferable but it's a bit complicated to achieve. This is an example where something like what I suggested in #3424 would be helpful.

**Comment by rusty-snake** [comment]
anyone fine?

**Comment by Fred-Barclay** [comment]
Oops, sorry! I'll try to get this updated ASAP!

**Comment by Fred-Barclay** [comment]
Updated! @rusty-snake as you mention mpv has a screenshot function that saves to $HOME I wonder if we should go back to blacklisting for this one?

**Comment by Fred-Barclay** [comment]
@rusty-snake thanks, gotten a little rusty here, should have kept the whitelist as well...

**Comment by rusty-snake** [comment]
https://github.com/netblue30/firejail/commit/deb6c12454191b7aeff3d259612a00427d1aa6a1#diff-74e11ae375b6951607bb9f53d646c4e4


`~/.config/mpv/foobar.conf`:
```
screenshot-directory=~/Pictures
```

**Pull request merged**
