### PR TITLE
New profile: Librewolf Nightly

### PR DESCRIPTION
**Pull request by vnepogodin**
Librewolf with Firefox Nightly base
https://aur.archlinux.org/packages/librewolf-nightly/

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]
LGTM, thanks!

**Review by rusty-snake — APPROVED** [review]
LGTM.
Just asking to be sure: There is nothing like `${HOME}/.librewolf-nightly`, right?

**Review by rusty-snake — APPROVED** [review]
LGTM
Just asking to be sure: There is nothing like `${HOME}/.librewolf-nightly`, right?

**Comment by vnepogodin** [comment]
Yes

**Comment by BL4CKH47H4CK3R** [comment]
Great Addition :heart:

**Comment by rusty-snake** [comment]
merged, thanks.

**Pull request merged**
