### PR TITLE
New profile: clac

### PR DESCRIPTION
**Pull request by glitsj16**
clac
Simple command-line calculator
https://github.com/alex-laycalvert/clac

Note: the app has no configuration.

### CODE REVIEW

**Review by rusty-snake — CHANGES_REQUESTED** [review]
The profile name / binary name conflicts with other programs. `calc` in fedora is https://isthe.com/chongo/tech/comp/calc/ for example.

**Comment by glitsj16** [comment]
@rusty-snake This app (and its binary) is called `clac`, not `calc`. How does that imply a name clash? Or does Fedora have anything already named `clac`?

**Comment by glitsj16** [comment]
@rusty-snake The name is indeed a bit awkward, no argument there. Thanks for the review and for pointing this out. If you'd prefer not including this profile, I'll drop the PR. It was something I had in my custom profiles, it isn't a widely used app and I can return it to my custom set of 'fringe app' profiles without any trouble :)

I'll leave this open for a while without merging so we can think about how we'd prefer to deal with these kind of apps.

**Comment by rusty-snake** [comment]
No, I've no problem with a clac profile. A ambiguous calc profile (with firecfg) would be a probelm.

**Pull request merged**
