### PR TITLE
Various

### PR DESCRIPTION
**Pull request by Fred-Barclay**
Gitter now has a profile.
I was looking into src/firecfg/firecfg.conf and realised that several profiles weren't mentioned in it. I've added them and alphabetised the file.

I also alphabetised the security filters in all the profiles, to hopefully make them even easier to read. There were a few redundancies (weechat had netfilter twice IIRC) so they *should* be gone as well. :wink: 
Hope this helps!

### CODE REVIEW

**Comment by KellerFuchs** [comment]
FWIW, I'm not sure that alphabetizing all profiles makes them easier to read: for instance, most profiles currently have `protocol` and `netfilter` next one to another because they are both network related.
With the alphabetization, I would have to scan through the whole file to find the 2 lines relevant to network.

**Comment by Fred-Barclay** [comment]
Perhaps so. Maybe I shouldn't say "easier" as an absolute--it's easier for me at any rate. :D

**Comment by netblue30** [comment]
Merged! It didn't make it however in 0.9.40,

**Comment by Fred-Barclay** [comment]
Thanks netblue30. 
BTW: what's the difference between the red "closed" tag after you merged this PR, and the normal purple "merged" tag? Is there something I should do to make it more consistent?

**Comment by netblue30** [comment]
It was a manual merge, the automatic one didn't work because of the release I made after you submitted the pull request. So, all is fine, just github getting confused.

**Comment by Fred-Barclay** [comment]
Thanks mate. :)

**Comment by avoidr** [comment]
I wanted to say the same as KellerFuchs, but I didn't, because I was too busy wetting my pillow and did not prevent a catastrophe in the profile environment and now it's all dirty and there's smog all over the place, but now I need to go to the bakery.
Terrible.

**Comment by Fred-Barclay** [comment]
@avoidr Ouch! Sorry, mate. :) I do wish you had mentioned it a bit earlier... :laughing: 

Let's see what @netblue30 says. I like the newer setup though I can see the logic behind your concerns. It just got confusing when reading profiles having to skip around looking for filters instead of them being queued. At any rate, some of it (esp. the duplicates and the missing entries) needed to be fixed.

**Comment by netblue30** [comment]
I don't see the problem here, is a cleanup on 80 files. From time to time we need to do it, /etc/firejail seems to go up with 30 new files per release. Thanks for the patch.

**Pull request closed without merging**
