### PR TITLE
docs: use GitHub issues as the bug reporting address

### PR DESCRIPTION
**Pull request by tredondo**

### CODE REVIEW

**Review by rusty-snake — CHANGES_REQUESTED** [review]
`configure` should not be edited directly, instead `configure.ac` should be edited and `configure` regenerated.

**Review by kmk3 — COMMENTED** [review]
```diff
-# Copyright (C) 1992-1996, 1998-2017, 2020-2021 Free Software Foundation,
+# Copyright (C) various years Free Software Foundation,
```

It would not be helpful (to say the least) to remove information from a
copyright statement (especially for code you didn't write), so this change was
undone.

Additionally, note that this line is from another project, so it would
potentially also be a license violation.

**Review by kmk3 — COMMENTED** [review]
It looks like this parameter is intended to be an email address, probably to
allow people to contribute patches without needing an account, though I'm not
sure how often that happens.

We do not have a mailing list and the same email address is already listed on
README for reporting security vulnerabilities, so unless this email is used for
bug reports/patches, I suppose that it would make sense to reference just the
issue tracker.

@netblue30 Do you get bug reports/patches by email?

**Comment by netblue30** [comment]
I'm merging it as is, thanks @tredondo. I'll generate a new configure script.

**Pull request merged**
