### PR TITLE
Fix Spotify #1513

### LINKED ISSUE #1513: [Spotify] Blacklisting too restrictive - firejail 0.9.48
Hi, spotify version 1.0.49.125 on ArchLinux with firejail 0.9.48 would not start and I got 
`/usr/bin/spotify: line 2: /opt/spotify/spotify: Permission denied`

commenting out `blacklist /opt` and appending a `whitelist /opt/spotify` to a local `~/.config/firejail/spotify.profile` did the trick.

### PR DESCRIPTION
**Pull request by SpotComms**
Fixes #1513

### CODE REVIEW

**Comment by VladimirSchowalter20** [comment]
Maybe remove only `blacklist /opt`. There is very little probability that other dirs will be needed.

**Comment by SpotComms** [comment]
Those are already blocked by default.

**Comment by reinerh** [comment]
Is blacklisting /sbin needed with private-bin?

**Comment by SpotComms** [comment]
@reinerh it doesn't seem so, but on my system /sbin is just a symlink to /bin
```
firejail --profile=spotify.profile bash
bash-4.4$ ls /sbin
bash  ls  sh
```

**Comment by netblue30** [comment]
Merged, thanks.

**Pull request merged**
