### PR TITLE
various little profile fixes and enhancements

### PR DESCRIPTION
**Pull request by smitsohu**
- more novideo options, without any systematics. Works as in _worksforme_
- blacklist the clementine database  and configuration
- better privacy for the tor-browser

### CODE REVIEW

**Comment by smitsohu** [comment]
@SpotComms Thanks for the hint! I'll do the same with geary.

**Comment by Fred-Barclay** [comment]
Hi @smitsohu 
Thanks for the improvements!

For mediathekview, why does it need access to .java?
For the tor browser profile, adding `machine-id` certainly doesn't hurt... but since `private-etc` only contains fonts, machine-id won't end up having any effect (since both the real-life and spoofed /etc/machine-id file are invisible to the sandbox). 😄

**Comment by SpotComms** [comment]
@Fred-Barclay https://github.com/mediathekview/MediathekView is written in Java

also as a note .java is used for caching fonts and for preference storage (not commonly utilized though)

**Comment by smitsohu** [comment]
@Fred-Barclay Hahaha, you are right! I can drop the commit again.
Regarding the Mediathekview, also see #1377

**Comment by Fred-Barclay** [comment]
Merged, thanks!

**Pull request merged**
