### PR TITLE
Harden some profiles

### PR DESCRIPTION
**Pull request by SpotComms**
Hardens some profiles I added in #946 and some others.

Can we also get a per profile disable-mnt? Also what exactly are the side-effects of 'ipc-namespace'?

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
Hi @SpotComms 
Thanks for the pull request!

Are you aware that commenting out the protocol and seccomp lines actually weakens the sandbox? 😉

**Comment by SpotComms** [comment]
Yes, those Java apps (JD-GUI, PDFSam, MultiMC5) don't appear to start anymore (they used to) with that, I couldn't figure out why. And seccomp is breaking MultiMC5 for some reason.

**Comment by Fred-Barclay** [comment]
I just read through everything and it all looks really good! But just to check before it's merged, does it all work or are you still having some issues with certain computers?

**Comment by SpotComms** [comment]
@Fred-Barclay so all of the profiles except for the 3 that use Java work. The 3 that use Java only seem to work on my desktop when using Wayland and not when using Xorg, which is odd because they work fine on other computers. But nothing that is broken was added in this commit, as in those protocol lines have been in master for a while now.

**Comment by Fred-Barclay** [comment]
If you're having trouble with Wayland I wonder if `no3d` is the cause?

**Comment by SpotComms** [comment]
@Fred-Barclay no thats the thing, its the exact opposite. The programs *are* working under wayland and not under xorg. And I've already tried the profiles without any of those changes, *and* they work just fine on other computers with wayland or xorg.

**Comment by Fred-Barclay** [comment]
Oh, okay. That's weird.
One last question - did the program work on that computer with the old profiles? I think you said so but I want to be double-sure. 😄

**Comment by SpotComms** [comment]
@Fred-Barclay to confirm, the 3 programs did work on the computer in question as of a ~month ago, and they've worked and are still working on others.

**Comment by Fred-Barclay** [comment]
Great - let's merge 'em in.
Thanks!

**Pull request merged**
