### PR TITLE
xz decompressor

### PR DESCRIPTION
**Pull request by kouul**
Decompressing .xz file within a sandboxing environment.

### CODE REVIEW

**Comment by reinerh** [comment]
What about network access? Sounds like this can be dropped too.

**Comment by Fred-Barclay** [comment]
Looks nice! :) A couple of quick suggestions:
Did you develop this on an older version of firejail? disable-mgr and disable-secret aren't part of firejail's code anymore (they were replaced, I don't remember with what) so the profile won't work on the current firejail code. 
And like reinerh, I think that dropping network access, or at least using `netfilter`, would help too.

Nice work!

**Comment by avoidr** [comment]
Also `nonewprivs` and possibly `private-bin`, `private-etc`, or `private-dev`.

**Comment by netblue30** [comment]
Merged, thanks.

**Pull request merged**
