### PR TITLE
Fix wget breaking rkhunter

### PR DESCRIPTION
**Pull request by SpotComms**
Not the best way, suggestions?

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
IMHO it would be better to set up a separate rkhunter profile. We probably don't want to expose /var/lib/rkhunter/tmp as read-write to all programmes using wget. 

Cheers and thanks!
Fred

**Comment by SpotComms** [comment]
I'll try to make one, my worry is that the sandbox even with features all disabled might cause rkhunter to not be able to scan properly.

**Comment by Fred-Barclay** [comment]
How do you normally run rkhunter in firejail?

**Comment by SpotComms** [comment]
I don't? But firecfg adds wget to /usr/local/bin, which rkhunter uses to update its signatures. So when rkhunter runs it tries to download updates to /var/lib/rkhunter/tmp which breaks since wget can't access that.

**Comment by Fred-Barclay** [comment]
Oh, I see. Well, a rkhunter.profile with only `read-write /var/lib/rkhunter/tmp` should do fine, then. That way, when rkhunter calls wget, it will allow writing to that location.

**Pull request closed without merging**
