### PR TITLE
Gather shell selection code in one place

### PR DESCRIPTION
**Pull request by manevich**
Shell selection code scattered everywere in code and causes bugs like this https://github.com/netblue30/firejail/issues/703.
So:
* new `guess_shell` function
* shell selection done once (well, except join), kept in `cfg.shell` variable.
* check for `/bin/bash` in chroot re-enabled as check for `cfg.shell`

For now calls `guess_shell` independently; also I noted that join never honored `--shell` and `--shell=none`. Will try to fix this latter.

### CODE REVIEW

**Comment by manevich** [comment]
Sorry, just found bug in my code, `firejail --private-bin=something cmd` fails.
Please, refrain of merging this before I fix it.
Thanks.

**Comment by manevich** [comment]
Fixed, I just uncommented wrong line...

**Comment by manevich** [comment]
Now `--join` honors `--shell` option including `--shell=none`.
Everything works fine for me, no regressions that I aware of.

**Comment by netblue30** [comment]
Merged, thanks.

**Pull request merged**
