### PR TITLE
Fixes #2821, riot-desktop

### LINKED ISSUE #2821: /usr/bin/riot-desktop: line 3: 8 Trace/breakpoint trap (core dumped) electron /usr/lib/riot/ "$@"
Running riot-desktop firejail makes it crash with the following message:
> /usr/bin/riot-desktop: line 3: 8 Trace/breakpoint trap (core dumped) electron /usr/lib/riot/ "$@"

Thi started happening when both electron and riot-desktop got updated 3 or so days ago.

### PR DESCRIPTION
**Pull request by Bandie**
Making a PR of @rusty-snake 's fix.

### CODE REVIEW

**Comment by rusty-snake** [comment]
:+1: 
I'm just thinking if it might be better to add it to riot-web.profile rather the riot-desktop.profile, but I don't know where the difference is (I'm not using matrix).

**Comment by Bandie** [comment]
As I understand it riot-desktop needs riot-web as riot-desktop might be the electron thingy while riot-web is the real™ application. But not sure about that.

**Comment by veloute** [comment]
@rusty-snake riot-desktop.profile should be fine - riot-desktop is the electron (desktop app) side of riot, which is where the problem is.

**Comment by rusty-snake** [comment]
Merged, Thanks.

**Pull request merged**
