### PR TITLE
Add support for SELinux labeling

### PR DESCRIPTION
**Pull request by topimiettinen**
Running `firejail --noprofile --private-bin=bash,ls ls -1Za /usr/bin`
shows that the SELinux labels are not correct:
```
user_u:object_r:user_tmpfs_t:s0 .
     system_u:object_r:usr_t:s0 ..
user_u:object_r:user_tmpfs_t:s0 bash
user_u:object_r:user_tmpfs_t:s0 ls
```

After fixing this:
```
       system_u:object_r:bin_t:s0 .
       system_u:object_r:usr_t:s0 ..
system_u:object_r:shell_exec_t:s0 bash
       system_u:object_r:bin_t:s0 ls
```

Most copied files and created directories should now have correct
labels (bind mounted objects keep their labels). This is useful to
avoid having to change the SELinux rules when using Firejail.

### CODE REVIEW

**Comment by kris7t** [comment]
Can you add some (dummy) code to silence the unused variable warning when we don't `HAVE_SELINUX`? Currently, the build is broken due to `-Werror`, unfortunately.

**Comment by topimiettinen** [comment]
Sure, done.

**Comment by rusty-snake** [comment]
I uninstalled libselinux-devel to check this:
```
make[1]: Entering directory '/home/user/GIT/firejail/src/firejail'
gcc -ggdb  -O2 -DVERSION='"0.9.63"'  -DPREFIX='"/usr"' -DSYSCONFDIR='"/etc/firejail"' -DLIBDIR='"/usr/lib64"' -DBINDIR='"/usr/bin"'      -DHAVE_SECCOMP -DHAVE_GLOBALCFG -DHAVE_SECCOMP_H  -DHAVE_NETWORK -DHAVE_USERNS  -DHAVE_WHITELIST -DHAVE_SELINUX -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -pie -Wformat -Wformat-security -mindirect-branch=thunk -fstack-clash-protection -fstack-protector-strong  -c selinux.c -o selinux.o
selinux.c:27:10: fatal error: selinux/context.h: No such file or directory
   27 | #include <selinux/context.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:6: selinux.o] Error 1
```
Can you add this dependency to the README (and where else it's required).
For Fedora: `sudo dnf install libselinux-devel`

**Comment by topimiettinen** [comment]
Updated README and README.md.

**Pull request merged**
