### PR TITLE
viewnior.profile: allow accessing /usr/share/viewnior

### PR DESCRIPTION
**Pull request by NetSysFire**
Wanted to crop an image in viewnior, noticed it did not work, checked stdout and sure enough it was missing a whitelisted path.

### CODE REVIEW

**Review by kmk3 — APPROVED** [review]

**Review by rusty-snake — APPROVED** [review]

**Review by glitsj16 — APPROVED** [review]
LGTM

**Comment by glitsj16** [comment]
@kmk3 Shortly after merging this I received a notification that there was a CI error. Can you have a look at https://github.com/netblue30/firejail/actions/runs/2723946291 please?

**Comment by kmk3** [comment]
@glitsj16 commented [on Jul 23](https://github.com/netblue30/firejail/pull/5270#issuecomment-1193137564):

> @kmk3 Shortly after merging this I received a notification that there was a
> CI error. Can you have a look at
> https://github.com/netblue30/firejail/actions/runs/2723946291 please?

From the log of `build_and_test`:

```
TESTING: fnetfilter copy (test/fnetfilter/copy.exp)
spawn /bin/bash
rm outfile
runner@fv-az135-219:~/work/firejail/firejail/test/fnetfilter$ rm outfile
rm: cannot remove 'outfile': No such file or directory
runner@fv-az135-219:~/work/firejail/firejail/test/fnetfilter$ 
<ejail/test/fnetfilter$ fnetfilter test1.net outfile          
runner@fv-az135-219:~/work/firejail/firejail/test/fnetfilter$ cat outfile
*filter
# test1
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
# echo replay is handled by -m state RELATED/ESTABLISHED above
#-A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
-A INPUT -p icmp --icmp-type destination-unreachable -j ACCEPT
-A INPUT -p icmp --icmp-type time-exceeded -j ACCEPT
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT
# disable STUN
-A OUTPUT -p udp --dport 3478 -j DROP
-A OUTPUT -p udp --dport 3479 -j DROP
-A OUTPUT -p tcp --dport 3478 -j DROP
-A OUTPUT -p tcp --dport 3479 -j DROP
COMMIT
runner@fv-az135-219:~/work/firejail/firejail/test/fnetfilter$ TESTING ERROR 2
```

That doesn't make sense to fail because of the changes from this PR (and I
don't know of any CI checks that could be broken by such changes).

Also, I noticed that the commits before and after the merge of this PR passed
`build_and_test`:

* <https://github.com/netblue30/firejail/runs/7463875207>
* <https://github.com/netblue30/firejail/runs/7482376673>

So I re-ran the failed job from the merge and it passed now:

* <https://github.com/netblue30/firejail/actions/runs/2723946291>

To me it seems like it was an issue with the GitHub runners, especially
considering that the original run took 2m 30s while the new one took 8m 8s.

When some jobs fail and you think that the error seems bogus, you can re-run
them with:

* Go to the page of the failed run (such as at
  <https://github.com/netblue30/firejail/actions/runs/2723946291>)
* Click on Re-run jobs -> Re-run failed jobs (on the upper right corner)

By the way, the errors in the logs can be grepped with "TESTING ERROR " (mind
the space).

**Comment by kmk3** [comment]
> To me it seems like it was an issue with the GitHub runners, especially
> considering that the original run took 2m 30s while the new one took 8m 8s.

Though to be fair, it could possibly also be due to race conditions in the
tests (I haven't checked).

**Comment by glitsj16** [comment]
@kmk3 Thank you for your efforts to look into this. Very much appreciate your analysis and pointers on how to go about such CI notifications in the future.

**Comment by kmk3** [comment]
@glitsj16 commented [on Jul 24](https://github.com/netblue30/firejail/pull/5270#issuecomment-1193272012):

> @kmk3 Thank you for your efforts to look into this. Very much appreciate your
> analysis and pointers on how to go about such CI notifications in the future.

Glad to be of help :)

If you have any questions about CI, feel free to ask.

**Pull request merged**
