### PR TITLE
firefox-common-addons.inc: + tridactyl

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by rusty-snake** [comment]
@l29ah looks fine, but we never do `blacklist ${HOME}/.local/share/tridactyl` so you can remove line 22.

**Comment by Fred-Barclay** [comment]
@rusty-snake actually we should probably add `blacklist ${HOME}/.local/share/tridactyl` to disable-programs.inc and keep the noblacklist line here

**Comment by rusty-snake** [comment]
@Fred-Barclay that works, too, I had decided to remove it because we don't have it with most of the others (e.g. vimperator).

**Comment by rusty-snake** [comment]
@l29ah can you apply one of the advices, either the one I gave you, or rather the one @Fred-Barclay gave you.

**Comment by rusty-snake** [comment]
@l29ah

**Comment by rusty-snake** [comment]
Merged, Thanks.

**Pull request merged**
