### PR TITLE
Let programs outside librewolf sandbox open new tabs in librewolf

### PR DESCRIPTION
**Pull request by crocket**
This is a very simple pull request.

### CODE REVIEW

**Comment by kmk3** [comment]
Relates to #4538.

**Review by kmk3 — APPROVED** [review]

**Review by rusty-snake — APPROVED** [review]
I don't think we need a comment, anyway.

**Comment by crocket** [comment]
I deleted comment.

**Comment by rusty-snake** [comment]
Merged, thanks.

**Pull request merged**
