### PR TITLE
safeguard single line comments

### PR DESCRIPTION
**Pull request by glitsj16**
Using `-` on single line comments can break easily when users just uncomment a line. It's advised to use `#` instead.

Relates to https://github.com/netblue30/firejail/pull/5942

### CODE REVIEW

**Comment by rusty-snake** [comment]
TBH uncommenting lines can break easily if you update firejail.

**Comment by rusty-snake** [comment]
And :+1: for `#COMMAND` `# COMMENT` difference.

**Comment by kmk3** [comment]
@glitsj16

Ah you beat me to it :p

I also started working on this with a script (I probably should have commented
about it on a related PR), though it's only for the `# ` to `#` and fixing the
end-of-line comments (mostly no changes to existing normal comments).

It currently changes about ~220 files.

Do you mind if we try the automated way first and then continue with this PR
for whatever is missing?

**Comment by glitsj16** [comment]
> And 👍 for #COMMAND # COMMENT difference.

@rusty-snake Thanks. There's bound to be plenty of places left were we could streamline this. Perhaps we can add an item in the template so it's a bit more explicit for anyone who contributes and cares to actually follow the template.

> Do you mind if we try the automated way first and then continue with this PR
for whatever is missing?

@kmk3 Absolute not, feel free to proceed with your scripted version :+1: .

**Comment by glitsj16** [comment]
Let's close this now that #5987 takes over.

**Pull request closed without merging**
