### PR TITLE
add element-desktop redirect profile

### PR DESCRIPTION
**Pull request by glitsj16**
This PR accomodates the [name change](https://element.io/blog/welcome-to-element/) from Riot to Element.

### CODE REVIEW

**Comment by kortewegdevries** [comment]
How are you escaping the "(...)" in pathname?

**Comment by rusty-snake** [comment]
Why escaping?

**Comment by kortewegdevries** [comment]
Profile doesn't work in 0.9.62 was support included in 0.9.63?

**Comment by rusty-snake** [comment]
() is allowed since #3156.

**Comment by glitsj16** [comment]
> Profile doesn't work in 0.9.62 was support included in 0.9.63?

@kortewegdevries The name change was only introduced a few days ago, on July 15, so it's normal that you don't have this profile in 0.9.62. As @rusty-snake pointed out, there have been other changes that might explain why you can't run this in 0.9.62. Or are you testing with firejail from git and are experiencing issues?

**Comment by kortewegdevries** [comment]
No thanks, it works under current git. I was building a profile myself and I wasn't able to figure out how special characters were included in pathname.

**Comment by eighthave** [comment]
I tried this with 0.9.62, and got:
```console
$ /usr/bin/firejail /opt/Element/element-desktop
Reading profile /etc/firejail/element-desktop.profile
Error: "/.config/Element (Riot)" is an invalid filename
$ sed -i 's,\${HOME},/home/eighthave,g' /etc/firejail/element-desktop.profile
$ /usr/bin/firejail /opt/Element/element-desktop
Reading profile /etc/firejail/element-desktop.profile
Error: "/home/eighthave/.config/Element (Riot)" is an invalid filename
$
```

This seems to be triggered by `noblacklist`

**Comment by rusty-snake** [comment]
@eighthave this is not supported in 0.9.62. Read the comments above.

**Comment by kortewegdevries** [comment]
Note that this folder: `${HOME}/.config/Element (Riot)` isn't created any more after today's update,as far as I know. Some in ArchLinux room [said](https://matrix.to/#/!SEgsRQLScqPxYtucHl:archlinux.org/$NlnBOFLZAoCLjXx1myRmnvoLaf62Azc-S51-O76DFKE?via=archlinux.org&via=matrix.org&via=privacytools.io) and I checked.

**Comment by glitsj16** [comment]
> Note that this folder: ${HOME}/.config/Element (Riot) isn't created any more after today's update,as far as I know.

@kortewegdevries Thanks for the info. I'll check what's used on other OS'es and will drop it accordingly. If you want to get rid of it right now, you can always `blacklist` / `nowhitelist` ${HOME}/.config/Element (Riot) in a local override file.

**Pull request merged**
