### PR TITLE
Update vmware.profile & dbus-policy for amarok

### PR DESCRIPTION
**Pull request by Neo00001**
should I create `mkdir` entry for `/var/lib/vmware`?

### CODE REVIEW

**Comment by glitsj16** [comment]
> should I create mkdir entry for /var/lib/vmware?

The mkdir and mkfile options only apply to paths under ${HOME} AFAIK.

**Comment by rusty-snake** [comment]
manpage:

> Create  a  directory in user home, under /tmp, or under /run/user/<UID> before the sandbox is started.

**Review by rusty-snake — COMMENTED** [review]
amarok: Did you test the tray-icon? If not it maybe needs `dbus-user.own org.kde.*`.
vmware: agree to @glitsj16

**Comment by Neo00001** [comment]
> It might need `writable-var` though

should I add `writable-var`?



> amarok: Did you test the tray-icon? If not it maybe needs `dbus-user.own org.kde.*`

yep.tray-icon was working smoothly.no need for `dbus-user.own org.kde.*`. btw tested on Arch kde, if you think other de may need this then I will add it.

**Comment by Neo00001** [comment]
> should I add `writable-var`?

after going through there their documentation it seems `write` permission is needed.So adding it.

**Comment by Neo00001** [comment]
amarok's dbus-policy checked on gnome, will check on xfce later.Afaik, xfce's implementation is similar to gnome if not the same.

**Comment by netblue30** [comment]
> Should I merge this?

Absolutely! When you are done, you just merge it.

**Pull request merged**
