### PR TITLE
Streamline machine-id comment

### PR DESCRIPTION
**Pull request by glitsj16**

### CODE REVIEW

**Comment by Vincent43** [comment]
Isn't this too broad? Many apps can't play any audio.

**Comment by glitsj16** [comment]
@Vincent43 I was assuming that when an app can't play audio it might just as well have `machine-id` enabled. Give me a few hours to revert.

**Comment by reinerh** [comment]
Can you please squash your commits in the future?
Or if you really want to have one changed file per commit, name the affected profile in the commit subject.

**Comment by Vincent43** [comment]
@glitsj16 yes, enabling `machine-id` for apps which can't play audio is valuable. I was referring to comments which you added in this PR about possible audio break which may be confusing for users.

I think this comment fits best in a manpage.

**Comment by glitsj16** [comment]
People, my apologies for making a mess, lessons learned. Hopefully things are corrected now. I've added a small note to the machine-id stanza in man firejail. @reinerh Thanks for reminding me to squash, I'll keep it in mind in the future.

**Pull request merged**
