### PR TITLE
Remove shell none from profiles

### PR DESCRIPTION
**Pull request by rusty-snake**
Command: `sed -i "/^shell none/d" etc/*/*`

TODO:

```
etc/profile-a-l/beaker.profile:ignore shell none
etc/profile-a-l/default.profile:# shell none
etc/profile-a-l/fdns.profile:#shell none
etc/profile-a-l/gnome-nettool.profile:#shell none
etc/profile-a-l/jitsi-meet-desktop.profile:ignore shell none
etc/profile-m-z/pidgin.profile:# shell none
etc/profile-m-z/rocketchat.profile:ignore shell none
etc/profile-m-z/server.profile:# shell none
etc/templates/profile.template:#   OPTIONS (caps*, net*, no*, protocol, seccomp*, shell none, tracelog)
etc/templates/profile.template:#shell none
```

- manpage
- RELNOTES
- fbuilder

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]
LGTM

**Comment by glitsj16** [comment]
Now that shell is checked via passwd, should we ensure `private-etc` contains passwd?

**Comment by netblue30** [comment]
Thanks!

**Comment by kmk3** [comment]
Relates to #5196.

**Pull request merged**
