### PR TITLE
gajim: allow loading plugins

### PR DESCRIPTION
**Pull request by marek22k**
Closes https://github.com/netblue30/firejail/issues/5704

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]
LGTM. Thanks for the patch!

**Review by kmk3 — CHANGES_REQUESTED** [review]
Currently the commit message title is very long, which makes it stand out in
the git log:

```console
$ git show --pretty=%s -s
fix gajim, so that is loads plugins; closed https://github.com/netblue30/firejail/issues/5704
$ git show --pretty=%s -s @{u} | wc -m
94
```

The title is usually under 50~70 characters long; see the following for
details:

* <https://chris.beams.io/posts/git-commit/>

Can you amend the commit message to something like the following and
force-push?

```
gajim: allow loading plugins

Closes https://github.com/netblue30/firejail/issues/5704

Signed-off-by: Marek Küthe <m.k@mk16.de>
```

Example:

```sh
git commit --amend
# (edit it)
git push --force-with-lease
```

**Review by kmk3 — CHANGES_REQUESTED** [review]
The blank line between the title and the body is needed, otherwise git treats
both lines as being part of the title:

```console
$ git show --pretty='%s%n%n%b' -s
gajim: allow loading plugins Closes https://github.com/netblue30/firejail/issues/5704

Signed-off-by: Marek Küthe <m.k@mk16.de>
$ git show --pretty=%s -s
gajim: allow loading plugins Closes https://github.com/netblue30/firejail/issues/5704
$ git show --pretty=%s -s | wc -m
86
```

**Review by kmk3 — APPROVED** [review]
LGTM.

**Pull request merged**
