### PR TITLE
Test sort.py collate

### PR DESCRIPTION
**Pull request by kmk3**

### CODE REVIEW

**Review by glitsj16 — APPROVED** [review]
LGTM. I was a bit too late seeing this and assumed my sorting was broken.

**Comment by kmk3** [comment]
Sorry, I meant to open this on my own repository for testing.

Even when clicking to open the PR from there, for some reason GitHub defaults
to diregarding the current page and always opening the PR on the upstream for
some reason...

**Comment by kmk3** [comment]
So this PR doesn't actually work.

I looked at sort.py again after opening this and it seems that ignoring the
case is intentional (as it uses `casefold`):

```python
    items.sort(key=lambda s: s.casefold())
```

I would guess that the intent to make it easier to group similarly-named paths
on long `private-` lists.  Example:

```
private-bin awk,Bar,bar,cut,Foo,foo,grep
```

Though it does mean that it sees `Foo,foo` and `foo,Foo` as equivalent.

Either way, this is not just a simple bug as I had thought and I don't feel
like comparing the pros and cons of each sorting method at the moment, so I'm
closing this.

**Comment by kmk3** [comment]
Relates to #5368.

**Comment by rusty-snake** [comment]
IIRC I used casefold because case insensitive sorting was the current sorting used in the most profiles.

**Pull request closed without merging**
