### PR TITLE
ipc-namespace causing problems with file-roller

### PR DESCRIPTION
**Pull request by veloute**

### CODE REVIEW

**Comment by glitsj16** [comment]
@veloute Could you provide some more info on what you're seeing when launching file-roller? I'm trying to reproduce, but so far I haven't been able to. So far I've tested functionality with tar.bz2, tar.gz, tar.xz and zip. Works just fine here with the fire-roller.profile. I only see the warnings about dconf and D-Bus...

`
(file-roller:4): dconf-WARNING **: 12:25:26.073: failed to commit changes to dconf: Unknown or unsupported transport “DBUS_SESSION_BUS_ADDRESS=unix” for address “DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus”`

...which are cosmetic, as the produced archives look as expected. I'm not implying that `ipc-namespace` can't cause issues, just looking for reproducability.

**Comment by veloute** [comment]
with ipc-namespace enabled, file-roller will not launch at all.
the error:
`(file-roller:4): Gdk-ERROR **: 04:37:46.138: The program 'file-roller' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 180 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Parent is shutting down, bye...
`

**Comment by veloute** [comment]
also found ipc-namespace is causing issues with pavucontrol.

this has been an issue before for other profliles:
https://github.com/netblue30/firejail/issues/1300
https://github.com/netblue30/firejail/issues/1287
https://github.com/netblue30/firejail/issues/1331

**Comment by SkewedZeppelin** [comment]
Merged, thanks!

**Pull request merged**
