### PR TITLE
WIP: Recalibration of D-Bus access, see #1822

### PR DESCRIPTION
**Pull request by smitsohu**
A few notes:

- Atril I found broken without D-Bus, probably because it can't talk to its server process atrild anymore. Same for Xreader.
- SMPlayer uses the KDE file dialog, so we need to treat it like other KDE apps.
- Audacity, Kodi are not yet included here.

Still I am a bit unsure if we really can freeze application settings in some cases. Looking at the rich settings that gedit or rhythmbox expose (for a reason), can we make exceptions case by case?

### CODE REVIEW

**Comment by Fred-Barclay** [comment]
@smitsohu What about if we added a new file, disable-dbus.inc, with the lines:
```
apparmor
blacklist /run/user/*/bus
(*possibly* net none)
```
that way if a user needs to enable dbus for an application, they can just comment out one line instead of two to three, depending on which distro and version they're running?

**Comment by smitsohu** [comment]
@Fred-Barclay Yep. You are right, we should try to make it simpler.  We could do as you suggest, or alternatively maybe introduce a new profile option `nodbus`. For example we could parse the `protocol` line in order to figure out when installing a new disconnected network namespace is possible (basically all profiles have this line). Then we could check if $DBUS_SESSION_BUS_ADDRESS is a file and blacklist it. If $DBUS_SESSION_BUS_ADDRESS is not set we try to blacklist /run/user/$UID/bus, the default location.

**Comment by startx2017** [comment]
Voting for --nodbus, I'll give it a try this weekend.

**Comment by startx2017** [comment]
I have --nodbus on command line and "nodbus" in profiles. It will look for network namespaces and "unix" on protocol line and it will print a warning:
`````
$ firejail --nodbus
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 6313, child pid 6314
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 46.72 ms
`````
Commit: https://github.com/netblue30/firejail/commit/ae008e5fa9e8a901fbf255664f3de775415a39a3

**Comment by startx2017** [comment]
New commit: https://github.com/netblue30/firejail/commit/1ff6851a1a8dcb89f6cb4097b765167b0949a982

**Comment by Fred-Barclay** [comment]
@startx2017 Nicely done! Chrome and gpredict, at least, are working fine on my system with `--nodbus`.

**Comment by netblue30** [comment]
Quite cool, thanks! Let's start adding nodbus in the profiles, if something comes up we fix it in the code.

I tested it with gnome-terminal. gnome-terminal sends all its commands over dbus to be executed outside the sandbox - we blacklisted /usr/bin/gnome-terminal for this reason in disable-common.inc.

This is how it looks on Debian 7 (2013), Debian 9 (2017) and Arch:
`````
$ firejail --nodbus --noblacklist=/usr/bin/gnome-terminal --noblacklist=/bin/gnome-terminal gnome-terminal
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 2254, child pid 2255
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 40.03 ms
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Unknown or unsupported transport 'DBUS_SESSION_BUS_ADDRESS=unix' for address 'DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus'

Parent is shutting down, bye...
`````

**Comment by Fred-Barclay** [comment]
@smitsohu I meant to add just one commit (001c7e62c7703e80024b00d9dab7206d1deda985) to your branch but it looks like I added a whole bunch by mistake!

**Comment by smitsohu** [comment]
@Fred-Barclay :smile: No worries! I can just delete the branch, once you give me green light. No need to tidy up anything.

**Comment by Fred-Barclay** [comment]
Gopher it!

**Pull request closed without merging**
