### PR TITLE
added update scripts

### PR DESCRIPTION
**Pull request by Fred-Barclay**
For #1049 
I kept the `if [ $EUID != 0 ]; then...` bit - you might not need it (especially if this is called from firejail) but I figured it was better to have too much than to not send in enough. :)
I also added a `sleep 3` line so there's enough time for the user to see that firejail was updated.

Cheers!
Fred

### CODE REVIEW

**Comment by reinerh** [comment]
Some suggestions/comments:
- do a shallow clone (--depth 0), which is faster, and you don't need the history anyway
- please don't run everything as root (except the dpkg / make install)
- use "set -e" or check return codes, so that you don't run later commands that require previous commands to succeed. (for example there might already be a firejail directory where the user worked on; the git clone would then fail, but the directory would still be deleted, including the user's modifications / branches)
- I wouldn't install manually built software in /usr (software packaged by distros is installed there), but to /usr/local (which is the default and the usual location for manual installations).
- If you have the "sleep 3" to keep a terminal window open, I would move it at the end (after the cleanup).

**Comment by netblue30** [comment]
I'll try to grab it today, thanks @Fred-Barclay.

@reinerh - emergency release today to fix broken PulseAudio. The problem was introduced in 0.9.44.6.

**Comment by Fred-Barclay** [comment]
@netblue30 I was thinking of implementing some of @reinerh 's suggestions. Do you want me to do that and then you merge, or do you want to merge and then change it yourself?

@reinerh definitely, shallow cloning and `set -e` would be good to add (I didn't know about `set` so that's something new for me!). I'll drop the prefix for ./configure, since IIRC firejail assumes /usr/local to be the prefix if there is not one specificed .
I haven't found a reliable way to drop root within a script and then regain it. Any suggestions?

**Comment by netblue30** [comment]
> I was thinking of implementing some of @reinerh 's suggestions. Do you want me to do that and then you merge, or do you want to merge and then change it yourself?

Sure, go for it! I'll wait with the merge.

**Comment by reinerh** [comment]
@Fred-Barclay In #1049 someone suggested to just call "sudo make install" (and "sudo dpkg -i").
(And run nothing else as root)

**Comment by Fred-Barclay** [comment]
Okay, hopefully this looks a bit better. :grinning: 'set -e' is added, only the installation step runs as root, we only clone to depth 1 (apparently depth 0 is not possible if my error messages are to be believed), and we run in the sefault shell rather than requiring bash. I also removed the sleep 3 line - that's a leftover from my habbit of running my shell scripts by double-clicking and choosing "run in terminal" but it probably shouldn't have been here in the first place.

I did leave `./configure --prefix=usr` for the debian script since for some reason I think a plain `./configure` didn't make dpkg happy (it's been some time since I was running Debian so my memory may be faulty... please correct me if I'm wrong). 

I'm still a bit wonky with my understanding of `set` so I might not have used it correctly.

**Comment by reinerh** [comment]
Hi @Fred-Barclay,
thanks for updating your PR. :)
You are right, --depth requires at least 1, I confused that.
Looks good to me now. 👍

**Comment by Fred-Barclay** [comment]
Thanks @reinerh. 
Come to think of it, `mkdeb.sh` already has `configure --prefix=/usr`
https://github.com/netblue30/firejail/blob/master/mkdeb.sh#L21

Should I even call ./configure?

@netblue30 what's the proper protocol here?
```
git clone <firejail url>
cd firejail
./configure <maybe a prefix here?>
make
make deb
dpkg ...
```
or just simply ignore ./configure and make like this?
```
git clone <firejail url>
cd firejail
make deb
dkpg ...
```

**Comment by netblue30** [comment]
Merging tomorrow, but if you need more time let me know.

**Comment by Fred-Barclay** [comment]
No no, that's good. Merge away! :ship: 
I was wondering if you could anwer the question in my last post though. What's the proper procedure when compiling a .deb file?

**Comment by netblue30** [comment]
merged, thanks.

**Pull request merged**
