### PR TITLE
disable-common.inc: fix paths of slock and physlock

### PR DESCRIPTION
**Pull request by kmk3**
Added on commit f0adf06c3 ("disable-common.inc: more SUID", 2021-11-09).

Relates to #4668.

### CODE REVIEW

**Comment by kmk3** [comment]
(Opening a PR because I'm not 100% sure)

**Comment by rusty-snake** [comment]
If I `dnf provides <program>` in Fedora, it only finds `slock`.

**Comment by kmk3** [comment]
@rusty-snake commented [on Nov 12](https://github.com/netblue30/firejail/pull/4680#issuecomment-966858854):

> If I `dnf provides <program>` in Fedora, it only finds `slock`.

```console
$ pacman -Fl slock physlock | grep bin/
slock usr/bin/
slock usr/bin/slock
physlock usr/bin/
physlock usr/bin/physlock
```

**Review by reinerh — APPROVED** [review]

**Comment by netblue30** [comment]
merged, thanks!

**Pull request merged**
