### PR TITLE
Complete disable-common.inc

### PR DESCRIPTION
**Pull request by KellerFuchs**
This adds a number of things to `disable-common.inc`.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Removed a commit relative to `~/.password-store`, as I didn't notice `disable-passwdmgr.inc`

**Comment by netblue30** [comment]
Merged, thanks.

**Comment by KellerFuchs** [comment]
Well, thanks for making firejail in the first place.

**Comment by netblue30** [comment]
No problem. Thanks for all your pull requests, keep them coming!

**Pull request merged**
