### PR TITLE
Add Polari profile

### PR DESCRIPTION
**Pull request by jrabe**
Added a profile for [Polari](https://wiki.gnome.org/Apps/Polari), an IRC client for GNOME.

### CODE REVIEW

**Comment by netblue30** [comment]
Merged, thanks!

**Comment by jrabe** [comment]
@netblue30 For me, Firejail does not automatically load this profile even though it's in the same directory (`/etc/firejail`) as the other profiles. The file permissions are also identical. It works if I manually specify it with `profile=/etc/firejail/polari.profile`. Is this just me or is anyone else having this issue?

**Comment by netblue30** [comment]
Start polari in the sandbox, and add a --debug on the command line (firejail --debug polari). Cut&paste the output here.

**Comment by jrabe** [comment]
Thanks, I didn't realize `/usr/bin/polari` was a symlink to `/usr/share/polari/org.gnome.Polari`. Unfortunately, it seems like Firejail discards everything after the first dot and only uses `org` as the command name. Do you think it's possible to have Firejail check for the full file name if `org.profile` doesn't exist? (If you want, I'll look into that this weekend when I have more time and open a pull request.)

**Comment by jrabe** [comment]
Looks like GNOME uses `gapplication` to launch Polari (`gapplication launch org.gnome.Polari`). This makes checking the full profile name pretty useless, unfortunately.

**Comment by netblue30** [comment]
Moving the issue here: https://github.com/netblue30/firejail/issues/324

**Comment by jrabe** [comment]
Thanks! :+1:

**Pull request merged**
