### PR TITLE
Make some tests more robust

### PR DESCRIPTION
**Pull request by reinerh**

### CODE REVIEW

**Comment by netblue30** [comment]
Merged, thanks!

**Comment by netblue30** [comment]
I had to remove "cd /home" from test/environment/zsh.exp, csh.exp and rlimit-profile.exp. It was braking the test.

**Comment by reinerh** [comment]
Hm, without chaning the directory the test doesn't work when it's run in /tmp for example, because of pwd.
Do you have a different workaround for that?

**Comment by netblue30** [comment]
We can take out pwd. I'll give it a try under /tmp.

**Comment by netblue30** [comment]
"make test-environment" is fixed. I'll bring in a number of similar fixes for all other tests, I'll make sure everything runs fine under /tmp.

**Pull request merged**
